# Generated by Django 3.1.6 on 2021-02-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
