# Generated by Django 3.1.6 on 2021-02-06 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='url',
        ),
    ]
